#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pynative.pynative import PyNative
from pynative.views import *

pygna = PyNative()

@pygna.flask.route('/image/<imagename>.<imagetype>')
def getImage(imagename, imagetype):
	print "hey %s %s" % (imagename, imagetype)
	return pygna.getImage(imagename + "." + imagetype, imagetype)

# @pygna.flask.route('/icon/<imagename>')
# def getImage(imagename, imagetype):
# 	return pygna.getImage(imagename, "icon")


@pygna.flask.route('/<requestedScreenname>', methods=['GET', 'POST'])
def interfaceBuilder(requestedScreenname):
    screen = Screen()

    imgpath = "/image/test.png"

    ckb = Checkbox("Checkbox")
    rdb = RadioGroup("Test radio group")
    rdb.add_choice("Choice 1", "value1")
    rdb.add_choice("Choice 2", "value2")
    rdb.add_choice("Choice 3", "value3")

    #img = ImageView(imgpath)

    screen.add_view(TextView("Ciao Mondo"))
    #screen.add_view(TextView(loremipsum))  #TODO controllare che io con firefox non vedo le checkbox dopo
    screen.add_view(ckb)
    screen.add_view(rdb)
    #screen.add_view(img)
    screen.add_view(Button("Avanti"))
    return pygna.render(screen)

if __name__ == "__main__":
    pygna.flask.run(host="0.0.0.0", debug=False)
